version: 1
update_configs:
  - directory: /
    package_manager: javascript
    update_schedule: live
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
