version: 1
update_configs:
- directory: "/"
  package_manager: javascript
  update_schedule: monthly
  version_requirement_updates: increase_versions
  automerged_updates:
  - match:
      dependency_type: all
      update_type: all
